# image: <+artifact.image>
image: nginx:latest
port: 80
replicas: 1
namespace: <+serviceVariables.namespace>
env_name: <+serviceVariables.env_name>
annotations: {harness.io/direct-apply:  "<+pipeline.variables.skip>"}